/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import registro.Directorio;

/**
 *
 * @author Emiliano
 */
public class Menu extends javax.swing.JFrame {
    private Directorio directorio = new Directorio();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jBuscar = new javax.swing.JMenu();
        jBuscarClientePorTelefono = new javax.swing.JMenuItem();
        jEditar = new javax.swing.JMenu();
        jEditarAgregarCliente = new javax.swing.JMenuItem();
        jEditarBorrarCliente = new javax.swing.JMenuItem();
        jSalir = new javax.swing.JMenu();
        jMenuSalir = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenu6.setText("File");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar2.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jBuscar.setText("buscar");

        jBuscarClientePorTelefono.setText("Buscar Cliente por telefono");
        jBuscarClientePorTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarClientePorTelefonoActionPerformed(evt);
            }
        });
        jBuscar.add(jBuscarClientePorTelefono);

        jMenuBar1.add(jBuscar);

        jEditar.setText("editar");

        jEditarAgregarCliente.setText("agregar cliente");
        jEditarAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarAgregarClienteActionPerformed(evt);
            }
        });
        jEditar.add(jEditarAgregarCliente);

        jEditarBorrarCliente.setText("borrar cliente");
        jEditarBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditarBorrarClienteActionPerformed(evt);
            }
        });
        jEditar.add(jEditarBorrarCliente);

        jMenuBar1.add(jEditar);

        jSalir.setText("salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jSalir.add(jMenuSalir);

        jMenuBar1.add(jSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jEditarBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarBorrarClienteActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BorrarCliente borrarCliente = new BorrarCliente(directorio);
        borrarCliente.setVisible(true);
        escritorio.add(borrarCliente);
        escritorio.moveToFront(borrarCliente);
    }//GEN-LAST:event_jEditarBorrarClienteActionPerformed

    private void jBuscarClientePorTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarClientePorTelefonoActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        BuscarCliente buscar = new BuscarCliente(directorio);
        buscar.setVisible(true);
        escritorio.add(buscar);
        escritorio.moveToFront(buscar);
    }//GEN-LAST:event_jBuscarClientePorTelefonoActionPerformed

    private void jEditarAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditarAgregarClienteActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        AgregarClientes addCliente = new AgregarClientes(directorio);
        addCliente.setVisible(true);
        escritorio.add(addCliente);
        escritorio.moveToFront(addCliente);
        
    }//GEN-LAST:event_jEditarAgregarClienteActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jSalirActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jBuscar;
    private javax.swing.JMenuItem jBuscarClientePorTelefono;
    private javax.swing.JMenu jEditar;
    private javax.swing.JMenuItem jEditarAgregarCliente;
    private javax.swing.JMenuItem jEditarBorrarCliente;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JMenu jSalir;
    // End of variables declaration//GEN-END:variables
}
